# Generated by Django 3.1.4 on 2021-01-05 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0041_auto_20201228_1235'),
        ('adminpanel', '0044_auto_20201210_1844'),
    ]

    operations = [
    ]
