# Generated by Django 3.1.4 on 2021-01-21 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0045_merge_20210105_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='IsSubscriptionCanceled',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Stripe_Subscription_Id',
        ),
    ]
